export interface Token { access_token: string; token_type: string; }
export interface UserResponse { user_id: number; username: string; display_name: string | null; }
export interface UserProfile { user_id: number; username: string; created_at: string; display_name: string | null; profile_picture_url: string | null; bio: string | null; favorite_settlement: string | null; favorite_faction: string | null; }
export interface UserUpdate { username?: string | null; display_name?: string | null; bio?: string | null; favorite_settlement?: string | null; favorite_faction?: string | null; }
export interface CraftingStations { settlement_id: number; weapons_workbench: boolean; armor_workbench: boolean; chemistry_station: boolean; cooking_station: boolean; power_armor_station: boolean; }
export interface Settlement { settlement_id: number; name: string; region: string | null; addon: string; description: string; map_image_url: string | null; how_to_obtain: string; notes: string | null; ref_id: string; wiki_url: string; crafting_stations: CraftingStations; }
export interface UserSettlementListItem { settlement_id: number; name: string; unlocked: boolean; people: number | null; food: number | null; water: number | null; power: number | null; defense: number | null; beds: number | null; happiness: number | null; }
export interface UserSettlementResponse { user_settlement_id: number; settlement_id: number; people: number; food: number; water: number; power: number; defense: number; beds: number; happiness: number; notes: string | null; }
export interface UserSettlementUpdate { people?: number | null; food?: number | null; water?: number | null; power?: number | null; defense?: number | null; beds?: number | null; happiness?: number | null; notes?: string | null; }
export interface UserSettlementDetail { user_settlement_id: number; settlement_id: number; people: number; food: number; water: number; power: number; defense: number; beds: number; happiness: number; notes: string | null; settlement: Settlement; }
